### ISSUE TITLE
代码折叠功能好像失效了

### ISSUE THREAD

**Issue by WangChao2021** [typora-community-plugin/typora-plugin-collapsible-section#2]
代码折叠功能好像失效了
![recording](https://github.com/user-attachments/assets/5dc1c178-c763-4045-bb73-b863c1a4b1f2)

Typora版本：1.9.5
typora-community-plugin 版本：2.0.20
collapsible-section 插件版本：1.5.2

**Comment by plylrnsdy** [comment]
可以啊，我的版本一样啊

**Comment by plylrnsdy** [comment]
我测试了一下，好像是 代码块的折叠模式 切换了保存不了，你看看是不是这个问题

**Comment by plylrnsdy** [comment]
修复了 代码块的折叠模式 切换了保存不了的问题

请更新 typora-community-plugin 到最新版本 2.1.3

你更新后，重新设置一下，看看还有没有问题

**Comment by WangChao2021** [comment]
> 修复了 代码块的折叠模式 切换了保存不了的问题
> 
> 请更新 typora-community-plugin 到最新版本 2.1.3
> 
> 你更新后，重新设置一下，看看还有没有问题

我的就是设置代码折叠不生效，晚点试下这个新的插件

**Comment by plylrnsdy** [comment]
又有个 bug😂

请更新 typora-community-plugin 到最新版本 2.1.4

**Comment by WangChao2021** [comment]
更新 typora-community-plugin 版本后，代码折叠还是失效的，我想会不会是因为我把插件左侧的活动栏给隐藏了，然后就打开了“显示活动栏”，代码折叠功能就恢复了。
目前看，代码折叠功能异常可能与“活动栏”的隐藏有关，我喜欢简单，一般都没有显示 活动栏

**Comment by plylrnsdy** [comment]
1. 更新 typora-community-plugin 版本后
2. 重新设置 代码折叠模式
3. 切换文档 或者 滚动一下当前文档，触发更新。才能看到效果

目前最新版本下，我测试后，无论是否显示活动栏都是可以保存代码折叠模式的

**Comment by WangChao2021** [comment]
> 1. 更新 typora-community-plugin 版本后
> 2. 重新设置 代码折叠模式
> 3. 切换文档 或者 滚动一下当前文档，触发更新。才能看到效果
> 
> 目前最新版本下，我测试后，无论是否显示活动栏都是可以保存代码折叠模式的

是的，新的版本下，我这边测试也没这个问题了

**Comment by WangChao2021** [comment]
老哥，在项目主页留个捐赠方式吧，真心想支持下你

**Comment by plylrnsdy** [comment]
> 更新 typora-community-plugin 版本后，代码折叠还是失效的，我想会不会是因为我把插件左侧的活动栏给隐藏了，然后就打开了“显示活动栏”，代码折叠功能就恢复了。
目前看，代码折叠功能异常可能与“活动栏”的隐藏有关，我喜欢简单，一般都没有显示 活动栏

那这个意思是这里 #3 的问题？

PS：“活动栏”其实可以切换更多面板的，不过目前只有 tag 有面板

**Comment by WangChao2021** [comment]
> > 更新 typora-community-plugin 版本后，代码折叠还是失效的，我想会不会是因为我把插件左侧的活动栏给隐藏了，然后就打开了“显示活动栏”，代码折叠功能就恢复了。
> > 目前看，代码折叠功能异常可能与“活动栏”的隐藏有关，我喜欢简单，一般都没有显示 活动栏
> 
> 那这个意思是这里 #3 的问题？
> 
> PS：“活动栏”其实可以切换更多面板的，不过目前只有 tag 有面板

是的， tag 功能我用的到是不频繁，对用tag比较频繁的场景，活动栏里的tag是高频使用场景

**Comment by plylrnsdy** [comment]
> 老哥，在项目主页留个捐赠方式吧，真心想支持下你

我研究研究 Github Sponsors，直接贴二维码不太好
