### ISSUE TITLE
关于代码块折叠的一点优化建议

### ISSUE THREAD

**Issue by WangChao2021** [typora-community-plugin/typora-plugin-collapsible-section#3]
插件的设置
![Snipaste_2024-08-12_16-23-15](https://github.com/user-attachments/assets/7af33ce2-3b60-4752-bb37-35a14e465feb)

当设置为 none 时，代码就不会折叠，想临时折叠也没法折叠，没有折叠按钮
![Snipaste_2024-08-12_16-24-32](https://github.com/user-attachments/assets/9ecf802c-58d3-4dfe-9b8e-87fa44f8b6bd)

有时候并不想文档里的所有代码都默认折叠，但遇到一大块的代码块，又想要只将它折叠起来，当前的实现无法满足这个场景。

建议再单独增加一个开关，控制是否启用代码折叠，已有的设置针对代码折叠块的默认设置。
![Snipaste_2024-08-12_16-28-28](https://github.com/user-attachments/assets/685e4fdd-2e8c-4ea8-a5f7-843aca659905)

就样就能实现，默认代码不折叠，但在查看文档时，可随时看代码折叠的设置进行折叠

**Comment by plylrnsdy** [comment]
那加个选项“是否自动折叠”

**Comment by WangChao2021** [comment]
> 那加个选项“是否自动折叠”

也可以的，只要能满足上面那种场景就好了，有些文档很多代码都只是1，2行命令，这种不需要默认折叠起来，只有遇到大块的代码，为了方便阅读文档，才需要临时折叠起来

**Comment by plylrnsdy** [comment]
请在“插件设置”对话框打开 → “已安装插件” → “检查更新”，并更新插件到 1.6.0

**Comment by WangChao2021** [comment]
> 请在“插件设置”对话框打开 → “已安装插件” → “检查更新”，并更新插件到 1.6.0

测试了下，很好用，比我之前描述的那个场景还更好用，能自动折叠超大代码块
