### ISSUE TITLE
[FR] Option to use it selectively

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-plugin-collapsible-section#5]
use case: I only want to collapse a particular H1 or H2 or Quote or Code block, not all of them…

**Comment by plylrnsdy** [comment]
you mean you need more commands?

like:
- Fold all H1
- Fold all H2
- Fold all H3
- Fold all H4
- Fold all H5
- Fold all H6

**Comment by thob** [comment]
Rather a way to only collopse/expand one particular h1 etc. which means it’s rather MD independent, i believe

**Comment by plylrnsdy** [comment]
Update it to 1.8.2. Now, you can fold/unfold h1~h6 & plain quoteblock by command
